version: '3.2'

services:
  db-inventory:
    networks:
      - my-app
    image: mongo
    ports:
      - "27017:27017"
  
  db-product:
    networks:
      - my-app
    image: mongo
    ports:
      - "27017:27017"

  db-order:
    networks:
      - my-app
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=order-database

  db-user:
    networks:
      - my-app
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=user-database

## User service
  user-service:
    networks:
      - my-app
    image: aanbari/user-service:latest
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - db-user
    environment:
      - SPRING_DATA_SOURCE_URL=jdbc:postgresql://db-user:5432/user-database
      - SPRING_DATA_SOURCE_USERNAME=admin
      - SPRING_DATA_SOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUT0=update

## Product service
  product-service:
    networks:
      - my-app
    image: aanbari/product-service:latest
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - db-product
      - kafka

## Order service
  order-service:
    networks:
      - my-app
    image: aanbari/order-service:latest
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - db-order
      - kafka

## Inventory service
  inventory-service:
    networks:
      - my-app
    image: aanbari/inventory-service:latest
    container_name: inventory-service
    ports:
      - "8083:8083"
    depends_on:
      - db-inventory
      - kafka


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - my-app

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
        - my-app


networks:
  my-app:
    driver: bridge