
INSERT INTO t_product (name, tag, description, price, created_at, updated_at)
VALUES
    ('Iphone 16 Pro Max', 'iphone-16-pro-max', 'Phone produced by Apple company', 12000, NOW(), NOW()),
    ('Iphone 16 Pro Max', 'iphone-16-pro-max', 'Phone produced by Apple company', 12000, NOW(), NOW()),
    ('Iphone 16 Pro Max', 'iphone-16-pro-max', 'Phone produced by Apple company', 12000, NOW(), NOW()),
    ('Iphone 16 Pro Max', 'iphone-16-pro-max', 'Phone produced by Apple company', 12000, NOW(), NOW()),
    ('Iphone 16 Pro Max', 'iphone-16-pro-max', 'Phone produced by Apple company', 12000, NOW(), NOW()),
    ('Samsung Galaxy S24 Ultra', 'samsung-galaxy-s24-ultra', 'Flagship phone by Samsung with AI features', 11000, NOW(), NOW()),
    ('MacBook Pro M3', 'macbook-pro-m3', 'Apple MacBook Pro with M3 chip and Retina display', 25000, NOW(), NOW()),
    ('Dell XPS 15', 'dell-xps-15', 'Premium Windows laptop with OLED display and Intel Core i9', 18000, NOW(), NOW()),
    ('Asus ROG Strix G17', 'asus-rog-strix-g17', 'High-performance gaming laptop with RTX 4080', 22000, NOW(), NOW()),
    ('Sony WH-1000XM5', 'sony-wh-1000xm5', 'Noise-canceling headphones with immersive sound quality', 3500, NOW(), NOW()),
    ('Apple AirPods Pro 2', 'airpods-pro-2', 'True wireless earbuds with active noise cancellation', 2000, NOW(), NOW()),
    ('Samsung Galaxy Buds 2 Pro', 'galaxy-buds-2-pro', 'Wireless earbuds with high-fidelity sound and ANC', 1900, NOW(), NOW()),
    ('Logitech MX Master 3S', 'logitech-mx-master-3s', 'Ergonomic wireless mouse with precision tracking', 1500, NOW(), NOW()),
    ('Razer BlackWidow V4', 'razer-blackwidow-v4', 'Mechanical gaming keyboard with RGB lighting', 2500, NOW(), NOW()),
    ('Corsair K100', 'corsair-k100', 'High-end gaming keyboard with OPX switches', 3000, NOW(), NOW()),
    ('Samsung T7 Shield SSD', 'samsung-t7-shield', 'Portable 2TB SSD with high-speed performance', 5000, NOW(), NOW()),
    ('WD Black SN850X', 'wd-black-sn850x', '1TB NVMe SSD for high-speed gaming', 4500, NOW(), NOW()),
    ('Seagate 5TB External HDD', 'seagate-5tb-hdd', 'Portable external hard drive for backups', 2000, NOW(), NOW()),
    ('BenQ EX3501R Monitor', 'benq-ex3501r', '35-inch curved ultrawide monitor with HDR support', 8500, NOW(), NOW()),
    ('LG OLED C2 TV', 'lg-oled-c2', '55-inch OLED 4K TV with Dolby Vision and HDMI 2.1', 16000, NOW(), NOW()),
    ('Samsung Odyssey G9', 'samsung-odyssey-g9', '49-inch ultrawide curved gaming monitor', 14000, NOW(), NOW()),
    ('PlayStation 5', 'ps5', 'Next-gen gaming console from Sony', 9000, NOW(), NOW()),
    ('Xbox Series X', 'xbox-series-x', 'Powerful gaming console by Microsoft', 8800, NOW(), NOW()),
    ('Nintendo Switch OLED', 'nintendo-switch-oled', 'Handheld gaming console with OLED display', 4500, NOW(), NOW()),
    ('GoPro Hero 12', 'gopro-hero-12', '4K action camera with stabilization', 5500, NOW(), NOW()),
    ('DJI Mini 3 Pro', 'dji-mini-3-pro', 'Compact drone with 4K camera', 8500, NOW(), NOW()),
    ('Sony Alpha A7 IV', 'sony-a7-iv', 'Mirrorless camera with 33MP sensor', 19000, NOW(), NOW()),
    ('Canon EOS R6', 'canon-eos-r6', 'Full-frame mirrorless camera with great low-light performance', 18000, NOW(), NOW()),
    ('Fitbit Charge 6', 'fitbit-charge-6', 'Fitness tracker with heart rate and GPS', 2200, NOW(), NOW()),
    ('Apple Watch Ultra 2', 'apple-watch-ultra-2', 'Rugged smartwatch for outdoor activities', 12000, NOW(), NOW()),
    ('Garmin Fenix 7', 'garmin-fenix-7', 'Multisport GPS smartwatch with long battery life', 13000, NOW(), NOW()),
    ('JBL Charge 5', 'jbl-charge-5', 'Portable Bluetooth speaker with powerful bass', 2800, NOW(), NOW()),
    ('Bose SoundLink Revolve', 'bose-soundlink-revolve', '360-degree portable speaker with deep sound', 3000, NOW(), NOW()),
    ('Echo Dot (5th Gen)', 'echo-dot-5', 'Smart speaker with Alexa voice assistant', 1800, NOW(), NOW()),
    ('Nest Hub (2nd Gen)', 'nest-hub-2', 'Smart display with Google Assistant', 3500, NOW(), NOW()),
    ('Philips Hue Smart Bulb', 'philips-hue-bulb', 'Color-changing LED bulb with smart control', 1200, NOW(), NOW()),
    ('TP-Link Deco X90', 'tplink-deco-x90', 'Mesh WiFi system for whole-home coverage', 11000, NOW(), NOW()),
    ('Netgear Nighthawk AX12', 'netgear-nighthawk-ax12', 'High-performance WiFi 6 router', 9500, NOW(), NOW()),
    ('Anker 737 Power Bank', 'anker-737-power-bank', 'Fast-charging 24,000mAh power bank', 3000, NOW(), NOW()),
    ('HyperX Cloud II', 'hyperx-cloud-ii', 'Comfortable gaming headset with 7.1 surround sound', 2500, NOW(), NOW()),
    ('SteelSeries Arctis Pro', 'steelseries-arctis-pro', 'High-resolution gaming headset with DAC', 3500, NOW(), NOW()),
    ('Epson EcoTank ET-3850', 'epson-ecotank-et3850', 'Wireless all-in-one printer with refillable ink', 6000, NOW(), NOW()),
    ('Roku Streaming Stick 4K', 'roku-streaming-stick-4k', '4K streaming device with Dolby Vision', 2500, NOW(), NOW()),
    ('Fire TV Cube', 'fire-tv-cube', 'Powerful streaming device with Alexa control', 4000, NOW(), NOW()),
    ('Google Pixel 8 Pro', 'google-pixel-8-pro', 'AI-powered flagship smartphone by Google', 10500, NOW(), NOW()),
    ('Oculus Quest 3', 'oculus-quest-3', 'Standalone VR headset with improved performance', 14000, NOW(), NOW()),
    ('MSI RTX 4090 GPU', 'msi-rtx-4090', 'High-end graphics card for gaming and AI workloads', 35000, NOW(), NOW()),
    ('AMD Ryzen 9 7950X', 'amd-ryzen-9-7950x', '16-core processor for extreme performance', 18000, NOW(), NOW()),
    ('Intel Core i9-13900K', 'intel-i9-13900k', 'Flagship Intel CPU for gaming and productivity', 17000, NOW(), NOW()),
    ('Corsair Vengeance 32GB RAM', 'corsair-vengeance-32gb', 'High-speed DDR5 RAM for gaming PCs', 6000, NOW(), NOW()),
    ('NZXT Kraken Z73', 'nzxt-kraken-z73', 'AIO liquid cooler with LCD display', 9000, NOW(), NOW());
